version: "3.8"

services:
  mysql:
    image: mysql:latest
    # ports:
    #   - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "app"

volumes:
  mysql_data: {}
