version: "3.8"

networks:
  sail:
    # driver: bridge

volumes:
  mysql_data: {}
  sail-mysql:
    # driver: local
  sail-redis:
    driver: local

services:
  hyperf:
    image: hyperf/hyperf:8.1-alpine-v3.18-swoole
    working_dir: /app
    entrypoint: composer install && php bin/hyperf.php start
    volumes:
      - ./hyperf:/app

  # laravel:
  #   build: ./laravel/.docker
  #   env_file: ./laravel/.env
  #   volumes:
  #     - "./laravel:/app"
  #   # ports:
  #   #   - "${BACKEND_PORT:-8000}:8000"
  #   networks:
  #     - sail

  # mongodb:
  #   image: mongo
  #   env_file: ./mongodb/.env

  # mysql:
  #   build: ./mysql
  #   env_file: ./mysql/.env
  #   # ports:
  #   #   - "3306:3306"
  #   networks:
  #     - sail

  # nest:
  #   image: node:20.11.1

  # nuxt:
  #   image: node:20.11.1
  #   working_dir: /app
  #   env_file: ./nuxt/.env
  #   command: bash -c "yarn install && yarn dev"
  #   ports:
  #     - 24678:24678
  #     - 3000:3000
  #   volumes:
  #     - "./nuxt:/app"

  # postgres:
  #   image: postgres
  #   env_file: ./postgres/.env
